### ISSUE TITLE
Delete & move

### ISSUE THREAD

**Issue by scenaristeur** [travis/concept#10]
Hi @travis , is there a way to delete or move pages ?thxs .

**Comment by travis** [comment]
Hi @scenaristeur! It's possible to delete pages using the hamburger menu in the upper right corner of the page UI. 

Moving pages isn't implemented yet - I'm not sure renaming directories is well supported by NSS at the moment, so it might take a little work. Definitely something I'd be excited about a patch for!

**Comment by travis** [comment]
opened #11 for move feature, closing
